export const INDUSTRIES = [
  "Any",
  "Accounting",
  "Advertising & Marketing",
  "Aerospace",
  "Agriculture",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Cybersecurity",
  "Data & Analytics",
  "E-commerce",
  "Education",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Fashion",
  "Financial Services",
  "Food & Beverage",
  "Gaming",
  "Government",
  "Healthcare",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "Legal",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Media & Publishing",
  "Mining",
  "Non-Profit",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "SaaS",
  "Security",
  "Sports",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "Venture Capital & Private Equity",
  "Web3 & Blockchain",
  "Other",
] as const;

export const DEPARTMENTS = [
  "Accounting",
  "Administrative",
  "Business Development",
  "Customer Support",
  "Data",
  "Design",
  "Engineering",
  "Finance",
  "Human Resources",
  "IT",
  "Legal",
  "Management",
  "Marketing",
  "Operations",
  "Product",
  "Project Management",
  "Quality Assurance",
  "R&D",
  "Research & Development",
  "Sales",
  "Security",
  "Supply Chain",
  "Support",
  "Training",
  "Other",
] as const;

export const COUNTRIES = [
  "Israel",
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "South Africa",
] as const;

