export const INDUSTRIES = [
  "Any",
  "Accounting",
  "Advertising & Marketing",
  "Aerospace",
  "Agriculture",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Cybersecurity",
  "Data & Analytics",
  "E-commerce",
  "Education",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Fashion",
  "Financial Services",
  "Food & Beverage",
  "Gaming",
  "Government",
  "Healthcare",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "Legal",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Media & Publishing",
  "Mining",
  "Non-Profit",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "SaaS",
  "Security",
  "Sports",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "Venture Capital & Private Equity",
  "Web3 & Blockchain",
  "Other",
] as const;

export const DEPARTMENTS = [
  "Software Engineering",
  "Frontend Engineering",
  "Backend Engineering",
  "Full-Stack Engineering",
  "Mobile Engineering",
  "Data Engineering",
  "Data Science",
  "Machine Learning / AI",
  "DevOps / SRE",
  "Cloud / Infrastructure",
  "Cybersecurity",
  "QA / Test Automation",
  "Product Management",
  "Product Design (UI/UX)",
  "Technical Program Management",
  "Solutions Engineering",
  "IT / Systems",
  "Technical Support",
  "Computer Science (student/graduate)",
  "Information Systems (student/graduate)",
  "Other (tech-related)",
] as const;

export const COUNTRIES = [
  "Israel",
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "South Africa",
] as const;

